#!/usr/bin/env ruby

# `avconv -i vid/mario.mp4 -r 30 vid/extracted/still_%04d.png`
Dir.glob('vid/extracted/*.png') do |image_name|
	output_name = image_name.gsub('extracted/', 'voronoi/')
	puts "Saving #{output_name}"
	`python main.py --image #{image_name} --render voronoi --save #{output_name}`
end